### ISSUE TITLE
pkg_resources.DistributionNotFound error in jaraco-text-4.0.0

### ISSUE THREAD

**Issue by ebocchi** [jaraco/jaraco.text#20]
Hi there,

A recent update of jaraco-text (from 3.2.0 to 4.0.0) seems to break calls from pkg_resources from python3-setuptools.

This is an example when trying to infer the version of cherrypy using:
- python3-jaraco-text-4.0.0
- python3-setuptools-53.0.0
- cherrypy-18.6.1 (https://github.com/cherrypy/cherrypy/blob/v18.6.1/cherrypy/__init__.py#L111-L114)

```
$ python3
	Python 3.9.18 (main, Oct  4 2024, 00:00:00) 
	[GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] on linux
	Type "help", "copyright", "credits" or "license" for more information.
	>>> import cherrypy
	>>> import jaraco.text
	>>> import pkg_resources
	>>> print (cherrypy.__version__)
	unknown
```

Unknown is reported due to the try-except in cherrypy code.
Without the try-except, this results in
```
	>>> pkg_resources.require('cherrypy')[0].version
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
		needed = self.resolve(parse_requirements(requirements))
	  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
		raise DistributionNotFound(req, requirers)
	pkg_resources.DistributionNotFound: The 'jaraco.text' distribution was not found and is required by jaraco.collections
```

I see latest version of cherrypy (18.10.0) infers its own version differently, which no longer uses pkg_resource and seems to work:
```
	try:
		__version__ = importlib_metadata.version('cherrypy')
	except Exception:
		__version__ = 'unknown'
```

Cannot tell if the same trackeback `pkg_resources.DistributionNotFound: The 'jaraco.text' distribution was not found and is required by jaraco.collections` would produce from other code paths, so I though it was worth reporting.

**Comment by cmonfort** [comment]
I'd say that all `jaraco-` modules have to be reviewed, because when I "fixed" the `jaraco.text` problem above on my system
(with `ln -s /usr/lib/python3.9/site-packages/jaraco_text-4.0.0.dist-info /usr/lib/python3.9/site-packages/jaraco.text-4.0.0.dist-info` to please python), another one pop up:
`pkg_resources.DistributionNotFound: The 'jaraco-functools' distribution was not found and is required by jaraco.text`

**Comment by jaraco** [comment]
I don't think there's anything that `jaraco.text` is doing wrong or could do differently. Consider the [differences between `jaraco.text` 3.14 and 4](https://github.com/jaraco/jaraco.text/compare/v3.14.0...v4.0.0). There are no changes to the implementation and only a change to the metadata (dependencies).

Really, the problem lies with `pkg_resources`, which is deprecated. Unfortunately, if you're stuck on an old CherryPy that depends on `pkg_resources`, you'll be stuck with those bugs.

I recommend instead to upgrade CherryPy. It tends to be pretty stable around updates.

You might search Setuptools for issues with pkg_resources, or even file one, but I'm fairly confident there's nothing that `jaraco.*` packages are doing improperly here and you're likely to be directed to migrate off `pkg_resources`.
