### ISSUE TITLE
3.5.0: sphinx warnings

### ISSUE THREAD

**Issue by kloczek** [jaraco/jaraco.text#5]
First of all after `setup.py build` to generate man page using sphinx it is necessarty to copy `jaraco/text/Lorem ipsum.txt` to `build/lib/jaraco/text/Lorem ipsum.txt`.
Without that sphinx-build barks:
```console
+ sphinx-build -b man -d jaraco-text docs .
Running Sphinx v3.5.4
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 2 added, 0 changed, 0 removed
reading sources... [100%] index
WARNING: autodoc: failed to import module 'text' from module 'jaraco'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 71, in import_module
    return importlib.import_module(modname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/tkloczko/rpmbuild/BUILD/jaraco.text-3.5.0/build/lib/jaraco/text/__init__.py", line 228, in <module>
    lorem_ipsum = resources.read_text(__name__, 'Lorem ipsum.txt')  # type: ignore
  File "/usr/lib64/python3.8/importlib/resources.py", line 169, in read_text
    with open_text(package, resource, encoding, errors) as fp:
  File "/usr/lib64/python3.8/importlib/resources.py", line 125, in open_text
    return TextIOWrapper(reader.open_resource(resource), encoding, errors)
  File "<frozen importlib._bootstrap_external>", line 988, in open_resource
FileNotFoundError: [Errno 2] No such file or directory: '/home/tkloczko/rpmbuild/BUILD/jaraco.text-3.5.0/build/lib/jaraco/text/Lorem ipsum.txt'
````
After manual copy that txt file still it is on warning
```console
+ /usr/bin/install -D 'jaraco/text/Lorem ipsum.txt' 'build/lib/jaraco/text/Lorem ipsum.txt'
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILD/jaraco.text-3.5.0/build/lib
+ sphinx-build -b man -d jaraco-text docs .
Running Sphinx v3.5.4
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 2 added, 0 changed, 0 removed
reading sources... [100%] index
/home/tkloczko/rpmbuild/BUILD/jaraco.text-3.5.0/build/lib/jaraco/text/__init__.py:docstring of jaraco.text.FoldedCase:50: WARNING: Unknown target name: "in".
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... jaraco-text.1 { history } done
build succeeded, 1 warning.
```

**Comment by jaraco** [comment]
I'm unsure why the docs build is failing to load 'Lorem ipsum.txt' in your environment. It is able to load in RTD builds, plus it's also tested by the CI and would cause the library to be completely non-viable if it didn't work as installed, so I'm not sure there's anything else this project can do to help. If you have ideas, feel free to share.

**Comment by kloczek** [comment]
Just checkedd new version and all looks clean now.
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.0.3
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 2 added, 0 changed, 0 removed
reading sources... [100%] index
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-jaraco-text.3 { history } done
build succeeded.
```

Thank you :)
