### ISSUE TITLE
Importing jaraco.text results in error

### ISSUE THREAD

**Issue by aptalca** [jaraco/jaraco.text#8]
Hi,

We publish a docker image for Mylar3, which uses cherypy and jaraco.text.

We noticed that the latest build with jaraco.text 3.6.0 results in the following error while importing jaraco.text:
```
Traceback (most recent call last):
  File "/app/mylar3/Mylar.py", line 26, in <module>
    import mylar
  File "/app/mylar3/mylar/__init__.py", line 39, in <module>
    import cherrypy
  File "/usr/lib/python3.9/site-packages/cherrypy/__init__.py", line 66, in <module>
    from ._cperror import (
  File "/usr/lib/python3.9/site-packages/cherrypy/_cperror.py", line 135, in <module>
    from cherrypy.lib import httputil as _httputil
  File "/usr/lib/python3.9/site-packages/cherrypy/lib/httputil.py", line 20, in <module>
    import jaraco.collections
  File "/usr/lib/python3.9/site-packages/jaraco/collections.py", line 10, in <module>
    import jaraco.text
  File "/usr/lib/python3.9/site-packages/jaraco/text/__init__.py", line 228, in <module>
    lorem_ipsum: str = files(__name__).joinpath('Lorem ipsum.txt').read_text()
AttributeError: 'PosixPath' object has no attribute 'read_text'
```

The docker image is based on alpine linux (tried both 3.13 and 3.14, one has py38 and the other py39 with the same result). We install jaraco.text via pip 21.3.1 (it's brought in as a dependency of cherrypy 18.6.1)

Here's the latest build log: https://ci.linuxserver.io/blue/organizations/jenkins/Docker-Pipeline-Builders%2Fdocker-mylar3/detail/master/133/pipeline/137#step-152-log-205
Here's the dockerfile: https://github.com/linuxserver/docker-mylar3/blob/master/Dockerfile#L44
And here's Mylar3's requirements.txt: https://github.com/mylar3/mylar3/blob/v0.5.9.5/requirements.txt#L11

If I uninstall jaraco.text 3.6.0 and install 3.5.1 in the same image, with everything else the same, it works fine.

Any ideas?

Thanks

**Comment by aptalca** [comment]
False alarm. The issue was due to a stray [pathlib.py](https://github.com/mylar3/mylar3/blob/v0.5.9.5/lib/pathlib.py)
